language: ruby
#bundler_args: --without production
before_install: gem update bundler --no-document
script: 'bundle exec rake test'
sudo: false

cache: bundler

rvm:
  - 2.4.1
  - 2.4.0
  - 2.3.3
  - 2.2.6

gemfile:
  - gemfiles/rails5_0.gemfile
  - gemfiles/rails5_1.gemfile

notifications:
  email: false

matrix:
  exclude:
    - rvm: 2.4.0
      gemfile: gemfiles/rails4_2.gemfile
  include:
    - rvm: 2.3.3
      gemfile: gemfiles/rails4_2.gemfile
    - rvm: 2.2.6
      gemfile: gemfiles/rails4_2.gemfile

fast_finish: true
