language: ruby
bundler_args: --without production
before_install: rm -f Gemfile.lock
sudo: false

matrix:
  include:
    - rvm: 2.2.0
      env: "RAILS_VERSION=4.2.0"
    - rvm: 2.2.3
      env: "RAILS_VERSION=4.2.4"

notifications:
  email: false
