language: ruby
sudo: false

bundler_args: --without production
before_install: gem update bundler --no-document
script: 'bundle exec rake test'

rvm:
  - 2.4.1
  - 2.4.0
#  - 2.3.3  # tested; reduce work for CI
#  - 2.2.6  # tested; reduce work for CI

gemfile:
  - gemfiles/rails5_0.gemfile
  - gemfiles/rails5_1.gemfile

matrix:
  exclude:
    - rvm: 2.4.0
      gemfile: gemfiles/rails4_2.gemfile
#  include:
#    - rvm: 2.3.3
#      gemfile: gemfiles/rails4_2.gemfile
#    - rvm: 2.2.6
#      gemfile: gemfiles/rails4_2.gemfile

notifications:
  email: false
fast_finish: true
