language: ruby
bundler_args: --without production
before_install: rm -f Gemfile.lock

rvm:
#  - 1.9.3
  - 2.2.0
#  - 2.2.3

env:
#  - "RAILS_VERSION=3.2.16"
#  - "RAILS_VERSION=4.1.6"
  - "RAILS_VERSION=4.2.4"

notifications:
  email: false
