language: ruby
bundler_args: --without production
# before_install: rm -f Gemfile.lock
sudo: false

rvm:
#  - 2.2.0
  - 2.3.1
#  - 2.4.0

gemfile:
  - Gemfile
  - gemfiles/rails4_2.gemfile

notifications:
  email: false
