language: ruby
sudo: false

bundler_args: --without production
before_install: gem update bundler --no-document
script: 'bundle exec rake test'

rvm:
  - 2.4.1
  - 2.4.0
#  - 2.3.3  # tested
#  - 2.2.6  # tested

gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile

matrix:
#  exclude:
#    - rvm: 2.4.0
#      gemfile: gemfiles/rails4_2.gemfile
#  include:
#    - rvm: 2.2.6
#      gemfile: gemfiles/rails4_2.gemfile

notifications:
  email: false
